Nyein/Controllers/MainPageController.cs
using Nyein.Common;
using Nyein.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Nyein.Controllers
{
    public class MainPageController : Controller
    {
        SqlDataAccess _conn = new SqlDataAccess();

        #region ConsumableProduct
        // GET: MainPage for ConsumableProduct
        [Route("Consumable")]
        public ActionResult Consumable()
        {
            try
            {
                SqlCommand cmd = new SqlCommand("SELECT * FROM Product WHERE ItemFlag='1' ORDER BY Id DESC", _conn.Connect());
                cmd.CommandType = CommandType.Text;
                SqlDataAdapter adp = new SqlDataAdapter(cmd);
                DataSet ds = new DataSet();
                adp.Fill(ds);
                cmd.CommandTimeout = 18000;
                _conn.Connect().Close();
                List<Product> lstProduct = ds.Tables[0].AsEnumerable().Select(row => new Product
                {
                    Id = Convert.ToInt32(row["Id"]),
                    Title = row["Title"].ToString(),
                    Description = row["Description"].ToString(),
                    Price = Convert.ToInt32(row["Price"]),
                    Image = row["Image"].ToString(),
                    ItemFlag = Convert.ToInt32(row["ItemFlag"])
                }).ToList();
                //Product product = new Product();
                //product.lstproducts = lstProduct;
                //return View(product);
                var lstImg = SelectForAllItem();
                Product model = new Product()
                {
                    lstproducts = lstProduct,
                    lstImage = lstImg
                };
                return View(model);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        public List<AllItem> SelectForAllItem()
        {
            try
            {
                SqlCommand cmd = new SqlCommand("SELECT * FROM Product ORDER BY Id DESC", _conn.Connect());
                cmd.CommandType = CommandType.Text;
                SqlDataAdapter adp = new SqlDataAdapter(cmd);
                DataSet ds = new DataSet();
                adp.Fill(ds);
                cmd.CommandTimeout = 18000;
                _conn.Connect().Close();
                List<AllItem> lstAllItem = ds.Tables[0].AsEnumerable().Select(row => new AllItem
                {
                    Image = row["Image"].ToString(),
                }).ToList();
                return lstAllItem;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        #endregion

        #region ConsumerGood
        //For Consumergoods product
        [Route("ConsumerGood")]
        public ActionResult ConsumerGood()
        {
            try
            {
                SqlCommand cmd = new SqlCommand("SELECT * FROM Product WHERE ItemFlag='2' ORDER BY Id DESC", _conn.Connect());
                cmd.CommandType = CommandType.Text;
                SqlDataAdapter adp = new SqlDataAdapter(cmd);
                DataSet ds = new DataSet();
                adp.Fill(ds);
                cmd.CommandTimeout = 18000;
                _conn.Connect().Close();
                List<Product> lstProduct = ds.Tables[0].AsEnumerable().Select(row => new Product
                {
                    Id = Convert.ToInt32(row["Id"]),
                    Title = row["Title"].ToString(),
                    Description = row["Description"].ToString(),
                    Price = Convert.ToInt32(row["Price"]),
                    Image = row["Image"].ToString(),
                    ItemFlag = Convert.ToInt32(row["ItemFlag"])
                }).ToList();
                //Product product = new Product();
                //product.lstproducts = lstProduct;
                //return View(product);
                Product model = new Product()
                {
                    lstproducts = lstProduct,
                    //popularProducts = lstpopularItem
                };
                return View(model);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        #endregion

        #region PopularProduct
        //Popular product
        public ActionResult Popular()
        {
            try
            {
                SqlCommand cmd = new SqlCommand("SELECT * FROM Product WHERE ItemFlag='0' ORDER BY Id DESC", _conn.Connect());
                cmd.CommandType = CommandType.Text;
                SqlDataAdapter adp = new SqlDataAdapter(cmd);
                DataSet ds = new DataSet();
                adp.Fill(ds);
                cmd.CommandTimeout = 18000;
                _conn.Connect().Close();
                List<Product> lstProduct = ds.Tables[0].AsEnumerable().Select(row => new Product
                {
                    Id = Convert.ToInt32(row["Id"]),
                    Title = row["Title"].ToString(),
                    Description = row["Description"].ToString(),
                    Price = Convert.ToInt32(row["Price"]),
                    Image = row["Image"].ToString(),
                    ItemFlag = Convert.ToInt32(row["ItemFlag"])
                }).ToList();
                var lstImg = SelectForAllItem();
                Product model = new Product()
                {
                    lstproducts = lstProduct,
                    lstImage = lstImg
                };
                return View(model);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        #endregion

        #region IndiaProduct
        //For Indian Perfume
        [Route("IndiaProduct")]
        public ActionResult IndiaProduct()
        {
            try
            {
                SqlCommand cmd = new SqlCommand("SELECT * FROM Product WHERE ItemFlag='3' ORDER BY Id DESC", _conn.Connect());
                cmd.CommandType = CommandType.Text;
                SqlDataAdapter adp = new SqlDataAdapter(cmd);
                DataSet ds = new DataSet();
                adp.Fill(ds);
                cmd.CommandTimeout = 18000;
                _conn.Connect().Close();
                List<Product> lstProduct = ds.Tables[0].AsEnumerable().Select(row => new Product
                {
                    Id = Convert.ToInt32(row["Id"]),
                    Title = row["Title"].ToString(),
                    Description = row["Description"].ToString(),
                    Price = Convert.ToInt32(row["Price"]),
                    Image = row["Image"].ToString(),
                    ItemFlag = Convert.ToInt32(row["ItemFlag"])
                }).ToList();
                //Product product = new Product();
                //product.lstproducts = lstProduct;
                //return View(product);
                Product model = new Product()
                {
                    lstproducts = lstProduct,
                    //popularProducts = lstpopularItem
                };
                return View(model);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        #endregion

        #region MyanmarProduct
        //For MyanmarPerfume
        [Route("MyanmarProduct")]
        public ActionResult MyanmarProduct()
        {
            try
            {
                SqlCommand cmd = new SqlCommand("SELECT * FROM Product WHERE ItemFlag='4' ORDER BY Id DESC", _conn.Connect());
                cmd.CommandType = CommandType.Text;
                SqlDataAdapter adp = new SqlDataAdapter(cmd);
                DataSet ds = new DataSet();
                adp.Fill(ds);
                cmd.CommandTimeout = 18000;
                _conn.Connect().Close();
                List<Product> lstProduct = ds.Tables[0].AsEnumerable().Select(row => new Product
                {
                    Id = Convert.ToInt32(row["Id"]),
                    Title = row["Title"].ToString(),
                    Description = row["Description"].ToString(),
                    Price = Convert.ToInt32(row["Price"]),
                    Image = row["Image"].ToString(),
                    ItemFlag = Convert.ToInt32(row["ItemFlag"])
                }).ToList();
                //Product product = new Product();
                //product.lstproducts = lstProduct;
                //return View(product);
                Product model = new Product()
                {
                    lstproducts = lstProduct,
                    //popularProducts = lstpopularItem
                };
                return View(model);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        #endregion

        #region AddToCartList
        //get addtoCart Items and show as List
        public ActionResult AddtoCartItem(AddtoCart model)
        {
            if (Session["Cart"] == null)
            {
                List<AddtoCart> lstAddCartItem = new List<AddtoCart>();
                lstAddCartItem.Add(model);
                Session["Cart"] = lstAddCartItem;
                Session["Count"] = 0;
            }
            else
            {
                List<AddtoCart> lstAddCartItem = (List<AddtoCart>)Session["Cart"];
                lstAddCartItem.Add(model);
                Session["Cart"] = lstAddCartItem;
                Session["Count"] = Convert.ToInt32(lstAddCartItem.Count);
            }
            return Json(JsonRequestBehavior.AllowGet);

        }
        #endregion

        #region RemoveAddToCart Item
        //Remove from AddtoCart
        public ActionResult RemoveAddtocartItem(AddtoCart model)
        {
            List<AddtoCart> lstItem = (List<AddtoCart>)Session["Cart"];
            lstItem.RemoveAll(i => i.Id == model.Id);
            Session["Cart"] = lstItem;

Nyein/Views/MainPage/AddtoCartItem.cshtml
@model IEnumerable<Nyein.Models.AddtoCart>

@{
    ViewBag.Title = "AddtoCartItem";
}

<h2>AddtoCartItem</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

Nyein/Views/MainPage/Cart_List.cshtml
@model IEnumerable<Nyein.Models.AddtoCart>
@using Newtonsoft.Json;
@{
    ViewBag.Title = "ငြိမ်းကွမ်းယာပစ္စည်း";
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="~/Content/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="apple-touch-icon" sizes="180x180" href="~/Content/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/Content/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/Content/fav/favicon-16x16.png">
    <meta name="theme-color" content="#ed970e">
    <link href="~/Content/mycss/css/shop-homepage.css" rel="stylesheet" />
    <link href="~/Content/mycss/css/style.css" rel="stylesheet" />
    <link href="~/Content/mycss/css/cart_list.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.0/css/mdb.min.css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet">
</head>
@if (Session["Cart"] == null)
{
<h1 class="text-center">စျေးခြင်းတောင်းထဲတွင်ပစ္စည်းမရှိပါ</h1>
}
else
{
    <body>
        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" style="background-color: #f8b140;">
            <a class="navbar-brand" href="#"><span style="font-weight: bold;font-family: 'Roboto', sans-serif;"><img src="~/Content/img/logo/nyein.jpg" alt="ငြိမ်း Official Logo" style=width:50px;height:50px> ငြိမ်းကွမ်းယာပစ္စည်း</span></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Popular","MainPage")">လူကြိုက်များထုတ်ကုန်</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Consumable","MainPage")">စားသုံးကုန် ပစ္စည်းများ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("ConsumerGood","MainPage")">လူသုံးကုန်ပစ္စည်းများ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("IndiaProduct","MainPage")">အန္ဒိယဆေးမွေးပစ္စည်းများ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("MyanmarProduct","MainPage")">မြန်မာဆေးရွကိကြီးပစ္စည်းများ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="~/about_us.html">ဝဘ်ဆိုက်အကြောင်း</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Contact</a>
                        </li>
                    </ul>
                </div>
        </nav>
        <!-- Page Content -->
        <br><br>
        <h4>ပစ္စည်းစာရင်း&nbsp;<i class="fas fa-clipboard-list"></i></h4><br>
        @*<h3>@Session["Count"]</h3>*@
        <!--First Card-->
        @foreach (var item in Model.GroupBy(s=>s.Title).Select(m=>m.First()).ToList())
        {

            @*<input type="hidden" id="no_1">@item.Id</input><br><br>*@
            <div class="shadow-lg p-3 mb-5 bg-white rounded" id="maindiv">
                <button class="btn btn-danger" id="delete_btn" onclick="deleteInternal('@JsonConvert.SerializeObject(item)')"><i class="far fa-trash-alt"></i></button>
                <div class="container" id="card_border">
                    <br><br>
                    <div class="row">
                        <!--First Card-->
                        <div class="col-lg">

                            <span id="cart_title">(ပစ္စည်းအမည်)<br><br><span id="title_@item.Id">@item.Title</span></span><br><br>
                        </div>
                        <div class="col-lg" id="item_quantity">
                            <span id="cart_title" class="allPrice">
                                (အရေအတွက်)<br><br>
                                <input type="number" value="1" min="1" max="100" step="1" id="qty_@item.Id" onchange="Calculate('@JsonConvert.SerializeObject(item)')" class="innerQty" />
                            </span><br><br>
                        </div>
                        <div class="col-lg" id="allPrice">
                            <span id="cart_title" class="allPrice">(စျေးနှုန်း)<br /><br /></span>
                                <div id="card-title"><span id="price_@item.Id" class="innerPrices">@item.Price KS</span></div>
</div>
                    </div><!--Finished First Card-->
                </div><!--Finished Container-->
            </div>
        }
        <!--Finished Card-->
        <div class="container">
            <div class="row">
                <div class="col-lg">
                    <h3 style="font-weight: 600;float:right" id="totalPrice"></h3><br><br>
                    <input type="hidden" id="getPrice" />
                    <div id="hid" style="color:white;"></div>
                </div>
            </div>
        </div>

        <center>
            <div class="col-lg"><button class="btn btn-success" id="order_btn" data-toggle="modal" data-target="#confirmModal" >Order တင်မည်။</button></div>
            <!--Confirm Modal-->
            <div class="modal fade" id="confirmModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="quantityModalLabel">Orderတင်ရန်သေချာပါသလား ?</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <!-- <div class="modal-body">
                        </div> -->
                        <div class="modal-footer">
                            <button type="button" id="modal_yes" class="btn btn-success" data-dismiss="modal" @*onclick="go_to_place_order();"*@ onclick="get_all_items_quantity();">သေချာပါပြီ။</button>
                            <button type="button" id="modal_no" class="btn btn-primary" data-dismiss="modal">မသေချာသေးပါ။</button>
                        </div>
                    </div>
                </div>
            
            </div><!--Finished Confirm Modal-->
        </center>
        <!-- Messenger Chat plugin Code -->
        <div id="fb-root"></div>

        <!-- Your Chat plugin code -->
        <div id="fb-customer-chat" class="fb-customerchat">
        </div>
        @* Messenger Plugin *@
        <script>
                    var chatbox = document.getElementById('fb-customer-chat');
                    chatbox.setAttribute("page_id", "112755027165266");
                    chatbox.setAttribute("attribution", "biz_inbox");

                    window.fbAsyncInit = function () {
                        FB.init({
                            xfbml: true,
                            version: 'v11.0'
                        });
                    };

                    (function (d, s, id) {
                        var js, fjs = d.getElementsByTagName(s)[0];
                        if (d.getElementById(id)) return;
                        js = d.createElement(s); js.id = id;
                        js.src = 'https://connect.facebook.net/my_MM/sdk/xfbml.customerchat.js';
                        fjs.parentNode.insertBefore(js, fjs);
                    }(document, 'script', 'facebook-jssdk'));
        </script>
        <!-- Copyright -->
        <br><br><br>
        <div class="footer-copyright text-center py-3">
            © @DateTime.Now.ToString("yyyy") Copyright:
            <a href="#" class="text-reset">www.nyeinshopping.com</a><br>
            <p><b><a href="https://www.nksoftwarehouse.com">Powered By NK Software House</a></b></p>
        </div>
        @{ 
            int i = 0;
            foreach(var item in Model)
            {
                i++;
                <script type="text/javascript">
                   sessionStorage.setItem(@i,@item.Id);
                </script>
                
            }
            <p id="session_count" style="display:none">@i</p>
        }

        <!-- Copyright -->
        <!-- Footer -->
        <!-- Bootstrap core JavaScript -->
        <script src="~/Content/vendor/jquery/jquery.min.js"></script>
        <script src="~/Content/vendor/bootstrap/js/bootstrap.min.js"></script>
        <!--Cart List JS-->
       <script type="text/javascript">
           function get_all_items_quantity(){
               var total_items=0;
               total_items=document.getElementById('session_count').innerText;  
               //console.log(total_items);
               var all_item_quantity_list="";
               for (i = 1; i <= total_items; i++){
                   all_item_quantity_list += document.getElementById("title_" + sessionStorage.getItem(i)).innerHTML + "/" + document.getElementById("qty_" + sessionStorage.getItem(i)).value + ",";
               }
               console.log(all_item_quantity_list);
               sessionStorage.setItem("all_items_quantity_list", all_item_quantity_list);
           }
           $(document).ready(function () {
               var totalPrice = 0;
               totalPrice +=@Html.Raw(Json.Encode(Model.Sum(x => x.Price)));
               document.getElementById('totalPrice').innerHTML = "Total:" + totalPrice + "KS";
               //For Processing
               document.getElementById('getPrice').value = totalPrice;

           });
           function TotalAmount(Id) {
               var FinalSum = 0;
               var FinalQty=0;
               var P = 0;
               getPrices = document.getElementById('price_' + Id).innerText;
               $('.innerPrices').each(function () {
                   FinalSum += parseInt($(this).text());
               });
               $('.innerQty').each(function () {
                   FinalQty += parseInt($(this).val());
               });
               document.getElementById('totalPrice').innerHTML = "Total:" + FinalSum + "KS";
               //For Processing
               document.getElementById('getPrice').value = FinalSum;
               document.getElementById('hid').innerHTML = FinalQty;
           }
           function Calculate(obj) {
               var sum = 0;
               var sumPrice = 0;
               sumPrice +=@Html.Raw(Json.Encode(Model.Sum(x => x.Price)));
               var Id = JSON.parse(obj).Id;
               var QtyId = $('#qty_' + Id).val();
               //console.log(sumPrice);
               var Price = JSON.parse(obj).Price;
               document.getElementById('price_' + Id).innerHTML = null;
               document.getElementById('price_' + Id).innerHTML = QtyId * Price +"KS";
               var total = QtyId * Price;
               var getprice = 0;
               $('#price_' + Id).each(function () {
                   getprice += parseInt($(this).text());
                   sum += (getprice + sumPrice) - Price;
               });
               TotalAmount(Id);
           }
           //auto refresh
           function doRefresh() {
               $('#maindiv').load('#maindiv');
               setTimeout(function () {
                   doRefresh();
               },500);
           }
           $(document).ready(function () {
               //doRefresh();
           })
           $('#modal_yes').click(function () {
               var totalPrice = $('#getPrice').val();
               var para = new URLSearchParams();
               para.append("getTotalPrice", totalPrice);
               location.href = "/mainpage/Order?" + para.toString();

               //var totalQty = document.getElementById('hid').innerText;
               //var para1 = new URLSearchParams();
               //para1.append("getTotalQty", totalQty);
               //location.href = "/mainpage/checkout?" + para1.toString();
           });
           function deleteInternal(obj) {
               var Id = JSON.parse(obj).Id;
               _modelId = {
                   Id:Id
               }
               $.ajax({
                   type: "POST",
                   url: '/MainPage/RemoveCardInternal',
                   data: { 'model': _modelId },
                   dataType: "JSON",
                   success: function () {
                       localStorage.removeItem(Id);
                       //window.location.href = "@Url.Action("Cart_List","MainPage")";
                       window.location.href='/Cart_List';
                   }
               });
           }
       </script>

        <script>
            AOS.init();
        </script>
    </body>
}
</html>

Nyein/Views/MainPage/OrderedCustomerList.cshtml
@model IEnumerable<Nyein.Models.AddtoCart>

@{
    ViewBag.Title = "ငြိမ်းကွမ်းယာပစ္စည်း";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="ငြိမ်းတွင် ကွမ်းယာပစ္စည်း ၊ အန္ဒိယဆေးမွေးပစ္စည်း ၊ မြန်မာဆေးရွက်ကြီးများ နှင့် လူသူံးကုန်ပစ္စည်းများကို ယုံကြည်စိတ်ချစွာ ဝယ်ယူနိုင်ပါသည်။">
<meta name="author" content="ငြိမ်းတွင် ကွမ်းယာပစ္စည်း ၊ အန္ဒိယဆေးမွေးပစ္စည်း ၊ မြန်မာဆေးရွက်ကြီးများနှင့် လူသုံးကုန်ကုန်ပစ္စည်းများကို ယုံကြည်စိတ်ချစွာ ဝယ်ယူနိုင်ပါသည်။">
<link rel="apple-touch-icon" sizes="180x180" href="~/Content/fav/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="~/Content/fav/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="~/Content/fav/favicon-16x16.png">
<meta name="theme-color" content="#ed970e">
<title>ငြိမ်းကွမ်းယာပစ္စည်း | Order List</title>
<link href="~/Content/mycss/admin.css" rel="stylesheet" />
<script src="~/Content/vendor/jquery/jquery.min.js"></script>
<script src="~/Content/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<body style="background-color:white">
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" style="background-color: #f8b140">
        <a class="navbar-brand" href="#"><span style="font-weight: bold;font-family: 'Roboto', sans-serif;"><img src="~/Content/img/logo/nyein.jpg" alt="ငြိမ်း Official Logo" style=width:50px;height:50px> ငြိမ်းကွမ်းယာပစ္စည်း</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="@Url.Action("ChooseService","AdminPanel")">
                        Choose Service
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
            </ul>
        </div>
    </nav>
    <br>
    <br>
    <br>
    <h4 class="text-center">Order စာရင်း<sup></sup>&nbsp;<i class="fas fa-clipboard-list"></i></h4>
    <br>
    <div class="container-fluid">
        <div class="table-responsive">
            <table class="table table-bordered">
                <tr>
                    <th>
                        ရက်/အချိန်
                    </th>
                    <th>
                        အမည်
                    </th>
                    <th>
                        ဖုန်းနံပါတ်
                    </th>
                    <th>
                        မြို့တော်
                    </th>
                    <th>
                        ရပ်ကွက်
                    </th>
                    <th>
                        လမ်း
                    </th>
                    <th>
                        ဘတ်စ်ကားမှတ်တိုင်
                    </th>
                    <th>
                        ပစ္စည်းအမည်
                    </th>
                    <th>
                        စုစုပေါင်း
                    </th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @item.OrderDate.ToString("dd/MM/yyyy hh:mm tt")
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Phone)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.city)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ward)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.street)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.busstop)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Item)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TotalPrice)
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>
    <br />
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">
        © @DateTime.Now.ToString("yyyy") Copyright:
        <a href="#" class="text-reset">www.nyeinshopping.com</a><br />
        <p>
            <b><a href="https://www.nksoftwarehouse.com">Powered By NK Software House</a></b>
        </p>
    </div>
    <!-- Copyright -->
</body>