Nyein/Controllers/AdminPanelController.cs
using Nyein.Common;
using Nyein.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Nyein.Controllers
{
    public class AdminPanelController : Controller
    {
        SqlDataAccess _conn = new SqlDataAccess();

        #region AdminPanel
        // GET: AdminPanel
        [Authorize]
        public ActionResult AdminPage()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AdminPage(Product model, HttpPostedFileBase[] files)
        {
            try
            {
                foreach (HttpPostedFileBase file in files)
                {
                    Random generator = new Random(); //get random number
                    string str = generator.Next(0, 10000).ToString("D5");//get 5 digit of random number
                    string FileName_ = Path.GetFileNameWithoutExtension(file.FileName);
                    string FileName = str + FileName_;
                    string FileExtension = Path.GetExtension(file.FileName);//file name casting to prevent duplicate name
                    var supportedExtension = new[] { ".jpg", ".jpeg", ".png" };//extension checking
                    if (!supportedExtension.Contains(FileExtension))
                    {
                        ViewBag.ErrorMessage = "File Extension Is InValid - Only Upload image format";
                        return ViewBag.ErrorMessage;
                    }
                    else
                    {
                        if (FileName != null)
                        {
                            string imageName = FileName.Trim() + FileExtension;
                            string imagePath = Path.Combine(Server.MapPath("~/Content/image"), imageName);
                            file.SaveAs(imagePath);
                            model.Image += imageName + " ";
                        }
                    }

                }
                string qurey = "INSERT INTO Product(Title,Description,Price,Image,Category,ItemFlag,UploadDate) VALUES(@Title,@Description,@Price,@Image,@Category,@ItemFlag,@UploadDate)";
                SqlCommand cmd = new SqlCommand(qurey, _conn.Connect());
                cmd.Parameters.AddWithValue("@Title", model.Title);
                cmd.Parameters.AddWithValue("@Description", DBNull.Value);
                cmd.Parameters.AddWithValue("@Price", model.Price);
                cmd.Parameters.AddWithValue("@Image", model.Image.TrimEnd(' '));
                cmd.Parameters.AddWithValue("@Category", model.Category);
                if (model.Category == "Consumable")
                {
                    cmd.Parameters.AddWithValue("@ItemFlag", 1);
                }
                if (model.Category == "ConsumerGoods")
                {
                    cmd.Parameters.AddWithValue("@ItemFlag", 2);
                }
                if (model.Category == "IndianPerfume")
                {
                    cmd.Parameters.AddWithValue("@ItemFlag", 3);
                }
                if (model.Category == "MyanmatPerfume")
                {
                    cmd.Parameters.AddWithValue("@ItemFlag", 4);
                }
                if (model.Category == "Popular")
                {
                    cmd.Parameters.AddWithValue("@ItemFlag", 0);
                }
                cmd.Parameters.AddWithValue("@UploadDate", DateTime.Now);
                cmd.ExecuteNonQuery();
                
                _conn.Connect().Close();
                TempData["Message"] = "True";
                return View();
            }
            catch (Exception ex)
            {
                return View();
            }
        }
        #endregion

        #region uploadedProductList
        //Get and display list for uploaded product by admin
        [Authorize]
        [Route("UploadedHistory")]
        public ActionResult UploadedProduct()
        {
            try
            {
                SqlCommand cmd = new SqlCommand("SELECT * FROM Product ORDER BY Id DESC", _conn.Connect());
                cmd.CommandType = CommandType.Text;
                SqlDataAdapter adp = new SqlDataAdapter(cmd);
                DataSet ds = new DataSet();
                adp.Fill(ds);
                cmd.CommandTimeout = 18000;
                _conn.Connect().Close();
                List<Product> lstProduct = ds.Tables[0].AsEnumerable().Select(row => new Product
                {
                    Id = Convert.ToInt32(row["Id"]),
                    Title = row["Title"].ToString(),
                    Price = Convert.ToInt32(row["Price"]),
                    Image = row["Image"].ToString(),
                    UploadDate = Convert.ToDateTime(row["UploadDate"])
                }).ToList();
                Product model = new Product()
                {
                    lstproducts = lstProduct
                };
                return View(model);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        #endregion

        #region DeleteItem
        //Delete Item
        public ActionResult Delete(int id)
        {
            string sql = "DELETE FROM Product WHERE Id=@Id";
            SqlCommand cmd = new SqlCommand(sql, _conn.Connect());
            cmd.Parameters.AddWithValue("@Id", id);
            cmd.ExecuteNonQuery();
            _conn.Connect().Close();
            TempData["DeletMessage"] = true;
            return Json(JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region ChooseService
        [Authorize]
        [Route("ChooseService")]
        public ActionResult ChooseService()
        {
            return View();
        }
        #endregion

        #region PopularProductHistory
        //Popular history
        public ActionResult PopularHistory()
        {
            try
            {
                SqlCommand cmd = new SqlCommand("SELECT * FROM Product WHERE ItemFlag='0' ORDER BY Id DESC", _conn.Connect());
                cmd.CommandType = CommandType.Text;
                SqlDataAdapter adp = new SqlDataAdapter(cmd);
                DataSet ds = new DataSet();
                adp.Fill(ds);
                cmd.CommandTimeout = 18000;
                _conn.Connect().Close();
                List<Product> lstProduct = ds.Tables[0].AsEnumerable().Select(row => new Product
                {
                    Id = Convert.ToInt32(row["Id"]),
                    Title = row["Title"].ToString(),
                    Description = row["Description"].ToString(),
                    Price = Convert.ToInt32(row["Price"]),
                    Image = row["Image"].ToString(),
                    ItemFlag = Convert.ToInt32(row["ItemFlag"])
                }).ToList();
                Product model = new Product()
                {
                    lstproducts=lstProduct
                };
                return View(model);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        #endregion

        #region ConsumableProductHistory
        //Consumable
        [Authorize]
        public ActionResult ConsumableHistory()
        {
            try
            {
                SqlCommand cmd = new SqlCommand("SELECT * FROM Product WHERE ItemFlag='1' ORDER BY Id DESC", _conn.Connect());
                cmd.CommandType = CommandType.Text;
                SqlDataAdapter adp = new SqlDataAdapter(cmd);
                DataSet ds = new DataSet();
                adp.Fill(ds);
                cmd.CommandTimeout = 18000;
                _conn.Connect().Close();
                List<Product> lstProduct = ds.Tables[0].AsEnumerable().Select(row => new Product
                {
                    Id = Convert.ToInt32(row["Id"]),
                    Title = row["Title"].ToString(),
                    Description = row["Description"].ToString(),
                    Price = Convert.ToInt32(row["Price"]),
                    Image = row["Image"].ToString(),
                    ItemFlag = Convert.ToInt32(row["ItemFlag"])
                }).ToList();
                Product model = new Product()
                {
                    lstproducts = lstProduct
                };
                return View(model);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        #endregion

        #region ConsumerGoodProductHistory
        //Consumergood
        [Authorize]
        public ActionResult ConsumerGoodHistory()
        {
            try
            {
                SqlCommand cmd = new SqlCommand("SELECT * FROM Product WHERE ItemFlag='2' ORDER BY Id DESC", _conn.Connect());
                cmd.CommandType = CommandType.Text;
                SqlDataAdapter adp = new SqlDataAdapter(cmd);
                DataSet ds = new DataSet();
                adp.Fill(ds);
                cmd.CommandTimeout = 18000;
                _conn.Connect().Close();
                List<Product> lstProduct = ds.Tables[0].AsEnumerable().Select(row => new Product
                {
                    Id = Convert.ToInt32(row["Id"]),
                    Title = row["Title"].ToString(),
                    Description = row["Description"].ToString(),
                    Price = Convert.ToInt32(row["Price"]),
                    Image = row["Image"].ToString(),
                    ItemFlag = Convert.ToInt32(row["ItemFlag"])
                }).ToList();
                Product model = new Product()
                {
                    lstproducts = lstProduct
                };
                return View(model);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        #endregion

        #region IndiaProductHistory
        [Authorize]
        public ActionResult IHistory()
        {

Nyein/Views/AdminPanel/AdminPage.cshtml
@model Nyein.Models.Product

@{
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="ငြိမ်းတွင် ကွမ်းယာပစ္စည်း ၊ အန္ဒိယဆေးမွေးပစ္စည်း ၊ မြန်မာဆေးရွက်ကြီးများ နှင့် လူသူံးကုန်ပစ္စည်းများကို ယုံကြည်စိတ်ချစွာ ဝယ်ယူနိုင်ပါသည်။">
<meta name="author" content="ငြိမ်းတွင် ကွမ်းယာပစ္စည်း ၊ အန္ဒိယဆေးမွေးပစ္စည်း ၊ မြန်မာဆေးရွက်ကြီးများနှင့် လူသုံးကုန်ကုန်ပစ္စည်းများကို ယုံကြည်စိတ်ချစွာ ဝယ်ယူနိုင်ပါသည်။">
<link href="~/Content/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
<link rel="apple-touch-icon" sizes="180x180" href="~/Content/fav/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="~/Content/fav/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="~/Content/fav/favicon-16x16.png">
<meta name="theme-color" content="#ed970e">
<title>ငြိမ်းကွမ်းယာပစ္စည်း | Upload Items</title>
<!--Sweet Alert-->
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
@using (Html.BeginForm("AdminPage", "AdminPanel", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    if (TempData["Message"] != null)
    {
<script>
            swal({
                title: 'Success!',
                icon: 'success',
                text: 'ပစ္စည်းအသစ်တင်ခြင်းအောင်မြင်ပါသည်',
                type: 'success',
                allowOutsideClick: false,
                confirmButtonColor: '#3085d6',
                confirmButtonText: 'Ok',
                allowEscapeKey: false
            }).then(function () {
            });
</script>
    }
    //else if (TempData["Message"] == null)
    //{
    //    Url.Action("/AdminPanel/AdminPage");
    //}
    else if (ViewBag.ErrorMessage != null)
    {
        <script>
            swal({
                title: 'အမျိုးအစားမှားယွင်းနေပါသည်',
                icon: 'error',
                text: 'ပုံသီးသန့်တင်ရန်ပြန်လည်ရွေးချယ်ပါ',
                type: 'error',
                allowOutsideClick: false,
                confirmButtonColor: '#3085d6',
                confirmButtonText: 'Ok',
                allowEscapeKey: false
            }).then(function () {
                //window.location = '/';
            });
        </script>
    }
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" style="background-color: #f8b140">
        <a class="navbar-brand" href="#"><span style="font-weight: bold;font-family: 'Roboto', sans-serif;"><img src="~/Content/img/logo/nyein.jpg" alt="ငြိမ်း Official Logo" style=width:50px;height:50px> ငြိမ်း Admin Panel</span></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="@Url.Action("ChooseService","AdminPanel")">
                            Choose Service
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                </ul>
            </div>
    </nav>
    <!-- Page Content -->
    <br />
    <br />
    <div class="container">
        <form>
            <div class="row">
                <div class="col-lg">
                    <select class="form-control form-control-lg" name="Category" id="_category" required="required">
                        <option value="All">Choose Category</option>
                        <option value="DisplayStand">Display Stand</option>
                        <option value="PromotionGift">Promotions Gift Item</option>
                        <option value="DigitalPackage">Digital Package</option>
                    </select>
                </div>
            </div><br />
            <div class="row">
                <div class="col-lg" id="DS_All">
                    <select class="form-control form-control-lg" name="Category" id="DS" required="required">
                        <option>Choose Sub Category</option>
                        <option value="AdapterSpeaker">Adapter_Speaker</option>
                        <option value="Bag">Bag</option>
                        <option value="Beauty">Beauty</option>
                        <option value="BlowSet">Blow Set</option>
                        <option value="CarAccessories">Car Accessories</option>
                        <option value="Consumable">စားသုံးကုန် ပစ္စည်းများ</option>
                        <option value="Clock">Clock</option>
                        <option value="Covid">Covid</option>
                        <option value="Cup">Cup</option>
                        <option value="Consumable">စားသုံးကုန် ပစ္စည်းများ</option>
                        <option value="ConsumerGoods">လူသုံးကုန်ပစ္စည်းများ</option>
                        <option value="IndianPerfume">အန္ဒိယဆေးမွေးပစ္စည်းများ</option>
                        <option value="MyanmatPerfume">မြန်မာဆေးရွကိကြီးပစ္စည်းများ</option>
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="col-lg" id="DS_dropdown">
                    <select class="form-control form-control-lg" name="Category" id="DS" required="required">
                        <option>Choose Sub Category</option>
                        <option value="Popular">လူကြိုက်များထုတ်ကုန်</option>
                        <option value="Consumable">စားသုံးကုန် ပစ္စည်းများ</option>
                        <option value="ConsumerGoods">လူသုံးကုန်ပစ္စည်းများ</option>
                        <option value="IndianPerfume">အန္ဒိယဆေးမွေးပစ္စည်းများ</option>
                        <option value="MyanmatPerfume">မြန်မာဆေးရွကိကြီးပစ္စည်းများ</option>
                    </select>
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-lg" id="PG_dropdown">
                    <select class="form-control form-control-lg" name="Category" id="PG" required="required">
                        <option>Choose Sub Category</option>
                        <option value="Popular">လူကြိုက်များထုတ်ကုန်</option>
                        <option value="Consumable">စားသုံးကုန် ပစ္စည်းများ</option>
                        <option value="ConsumerGoods">လူသုံးကုန်ပစ္စည်းများ</option>
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="col-lg">
                    <!--Choose Image-->
                    <div class="form-group">
                        <label for="image_upload">Upload Images</label>
                        <input type="file" class="form-control-file" id="image_upload" onchange="readURL(this);"
                               name="files" style="display: none" accept="image/*" required="required" multiple /><br />
                        <img src="~/Content/img/logo/image_upload.png" class="img-fluid" alt="Responsive image"
                             style="width: 180px" id="upload_image" onclick="browse();" />
                        <br /><br />
                    </div>
                    <br /><br />
                </div>
            </div>
            <div class="row">
                <!--Enter Product Title-->
                <div class="col-lg">
                    <input class="form-control form-control-lg" type="text" placeholder="Product Title" name="Title" id="_title" required="required" /><br />
                </div>
            </div>
            <div class="row">
                <!--Enter Price-->
                <div class="col-lg">
                    <input class="form-control form-control-lg" type="text" placeholder="Price (MMK)" name="Price" id="_price" required="required" /><br />
                </div>
            </div>
            <center>
                <button type="submit" class="btn btn-outline-success" id="send">Submit</button>
            </center>
        </form>
    </div>
    <br />
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">
        © @DateTime.Now.ToString("yyyy") Copyright:
        <a href="#" class="text-reset">www.nyeinshopping.com</a><br />
        <p>
            <b><a href="https://www.nksoftwarehouse.com">Powered By NK Software House</a></b>
        </p>
    </div>
    <!-- Copyright -->
    <!-- Footer -->
}
<script src="~/Content/vendor/jquery/jquery.min.js"></script>
<script src="~/Content/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
<script src="https://kit.fontawesome.com/56ace15d76.js" crossorigin="anonymous"></script>
<script>
    AOS.init();
</script>
<!--Browser Files-->
<script src="~/Scripts/js/aos/choose_image.js"></script>
<script>
    $('document').ready(function () {
        $('#DS_All').show();
        $('#DS_dropdown').hide();
        $('#PG_dropdown').hide();
    });
    $('#_category').change(function () {
        var selectedData = $('#_category').val();
        if (selectedData == "DisplayStand") {
            $('#DS_dropdown').show();
            $('#PG_dropdown').hide();
            $('#DS_All').hide();
        } else if (selectedData == "PromotionGift") {
            $('#DS_dropdown').hide();
            $('#DS_All').hide();
            $('#PG_dropdown').show();
        } else if (selectedData == "All") {
            $('#DS_All').show();
            $('#DS_dropdown').hide();
            $('#PG_dropdown').hide();
        }
        
    });
</script>

Nyein/Views/AdminPanel/ChooseService.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="ငြိမ်းတွင် ကွမ်းယာပစ္စည်း ၊ အန္ဒိယဆေးမွေးပစ္စည်း ၊ မြန်မာဆေးရွက်ကြီးများ နှင့် လူသူံးကုန်ပစ္စည်းများကို ယုံကြည်စိတ်ချစွာ ဝယ်ယူနိုင်ပါသည်။">
    <meta name="author" content="ငြိမ်းတွင် ကွမ်းယာပစ္စည်း ၊ အန္ဒိယဆေးမွေးပစ္စည်း ၊ မြန်မာဆေးရွက်ကြီးများနှင့် လူသုံးကုန်ကုန်ပစ္စည်းများကို ယုံကြည်စိတ်ချစွာ ဝယ်ယူနိုင်ပါသည်။">
    <link href="~/Content/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="apple-touch-icon" sizes="180x180" href="~/Content/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/Content/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/Content/fav/favicon-16x16.png">
    <meta name="theme-color" content="#ed970e">
    <title>ငြိမ်းကွမ်းယာပစ္စည်း | Admin Panel</title>
    <link href="~/Content/mycss/css/shop-homepage.css" rel="stylesheet" />
    <link href="~/Content/mycss/css/style.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.0/css/mdb.min.css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet">
    <link href="~/Content/mycss/admin.css" rel="stylesheet" />
    <script src="~/Content/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" style="background-color: #f8b140;">
       <a class="navbar-brand" href="#"><span style="font-weight: bold;font-family: 'Roboto', sans-serif;"><img src="~/Content/img/logo/nyein.jpg" alt="ငြိမ်း Official Logo" style=width:50px;height:50px> ငြိမ်း Choose Service</span></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Popular","MainPage")">လူကြိုက်များထုတ်ကုန်</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Consumable","MainPage")">စားသုံးကုန် ပစ္စည်းများ</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("ConsumerGood","MainPage")">လူသုံးကုန်ပစ္စည်းများ</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("IndiaProduct","MainPage")">အန္ဒိယဆေးမွေးပစ္စည်းများ</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("MyanmarProduct","MainPage")">မြန်မာဆေးရွကိကြီးပစ္စည်းများ</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="~/about_us.html">ဝဘ်ဆိုက်အကြောင်း</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Account/Login">LogOut</a>
                    </li>
                </ul>
            </div>
    </nav><br><br><br>
    <div class="text-center">
        <div class="container-fluid">
            <div class="row">
                <div class="shadow p-3 mb-5 bg-white rounded" data-aos="fade-right" data-aos-delay="300">
                    <div class="col-lg">
                        <button class="btn btn-warning" class="service_btn" onclick="window.location.href='@Url.Action("AdminPage","AdminPanel")'"><img src="~/Content/img/logo/admin.png" class="services_admin_img"><br>Admin Panel</button>
                    </div>
                </div>
                <div class="shadow p-3 mb-5 bg-white rounded" data-aos="fade-right" data-aos-delay="500">
                    <div class="col-lg">
                        <button class="btn btn-success" class="service_btn" onclick="window.location.href='@Url.Action("OrderedCustomerList","MainPage")'"><img src="~/Content/img/logo/order_list.png" class="services_admin_img"><br>Order List</button>
                    </div>
                </div>
                <div class="shadow p-3 mb-5 bg-white rounded">
                    <div class="col-lg">
                        <button class="btn btn-info" class="service_btn" onclick="window.location.href='@Url.Action("UploadedProduct","AdminPanel")'"><img src="~/Content/img/logo/history.png" class="services_admin_img"><br>History</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br />
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">
        © @DateTime.Now.ToString("yyyy") Copyright:
        <a href="#" class="text-reset">www.nyeinshopping.com</a><br />
        <p>
            <b><a href="https://www.nksoftwarehouse.com">Powered By NK Software House</a></b>
        </p>
    </div>
    <!-- Copyright -->
    <!-- Footer -->
</body>
</html>
<script>
    AOS.init();
</script>